// <auto-generated />
using System;
using System.Collections.Generic;
using CashTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CashTrack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210811013629_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CashTrack.Data.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("CatagoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Merchant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("CatagoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("CashTrack.Data.Entities.ExpenseCatagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Catagory")
                        .HasColumnType("integer");

                    b.Property<bool>("InUse")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCatagories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Catagory = 7,
                            InUse = false,
                            Name = "AAA"
                        },
                        new
                        {
                            Id = 2,
                            Catagory = 14,
                            InUse = true,
                            Name = "Airfare"
                        },
                        new
                        {
                            Id = 3,
                            Catagory = 5,
                            InUse = false,
                            Name = "Banjo"
                        },
                        new
                        {
                            Id = 4,
                            Catagory = 1,
                            InUse = true,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Catagory = 12,
                            InUse = true,
                            Name = "Car Insurance"
                        },
                        new
                        {
                            Id = 6,
                            Catagory = 12,
                            InUse = true,
                            Name = "Car Repairs"
                        },
                        new
                        {
                            Id = 7,
                            Catagory = 12,
                            InUse = true,
                            Name = "Car Stuff"
                        },
                        new
                        {
                            Id = 8,
                            Catagory = 12,
                            InUse = true,
                            Name = "Car Wash"
                        },
                        new
                        {
                            Id = 9,
                            Catagory = 3,
                            InUse = true,
                            Name = "Church"
                        },
                        new
                        {
                            Id = 10,
                            Catagory = 0,
                            InUse = true,
                            Name = "Clothing (Kids)"
                        },
                        new
                        {
                            Id = 11,
                            Catagory = 0,
                            InUse = true,
                            Name = "Clothing (Mitch)"
                        },
                        new
                        {
                            Id = 12,
                            Catagory = 0,
                            InUse = true,
                            Name = "Clothing (Sarah)"
                        },
                        new
                        {
                            Id = 13,
                            Catagory = 5,
                            InUse = true,
                            Name = "Cycling"
                        },
                        new
                        {
                            Id = 14,
                            Catagory = 4,
                            InUse = true,
                            Name = "Dentist"
                        },
                        new
                        {
                            Id = 15,
                            Catagory = 8,
                            InUse = true,
                            Name = "Diapers"
                        },
                        new
                        {
                            Id = 16,
                            Catagory = 2,
                            InUse = true,
                            Name = "Dining Out"
                        },
                        new
                        {
                            Id = 17,
                            Catagory = 12,
                            InUse = true,
                            Name = "DMV"
                        },
                        new
                        {
                            Id = 18,
                            Catagory = 4,
                            InUse = true,
                            Name = "Doctor (Kids)"
                        },
                        new
                        {
                            Id = 19,
                            Catagory = 4,
                            InUse = true,
                            Name = "Doctor (Mitch)"
                        },
                        new
                        {
                            Id = 20,
                            Catagory = 4,
                            InUse = true,
                            Name = "Doctor (Sarah)"
                        },
                        new
                        {
                            Id = 21,
                            Catagory = 4,
                            InUse = true,
                            Name = "Drugs"
                        },
                        new
                        {
                            Id = 22,
                            Catagory = 5,
                            InUse = true,
                            Name = "Drums"
                        },
                        new
                        {
                            Id = 23,
                            Catagory = 13,
                            InUse = true,
                            Name = "Electricity"
                        },
                        new
                        {
                            Id = 24,
                            Catagory = 6,
                            InUse = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 25,
                            Catagory = 10,
                            InUse = true,
                            Name = "Fees"
                        },
                        new
                        {
                            Id = 26,
                            Catagory = 6,
                            InUse = true,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 27,
                            Catagory = 6,
                            InUse = true,
                            Name = "Games"
                        },
                        new
                        {
                            Id = 28,
                            Catagory = 5,
                            InUse = false,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 29,
                            Catagory = 12,
                            InUse = true,
                            Name = "Gas"
                        },
                        new
                        {
                            Id = 30,
                            Catagory = 3,
                            InUse = true,
                            Name = "Gifts"
                        },
                        new
                        {
                            Id = 31,
                            Catagory = 2,
                            InUse = true,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 32,
                            Catagory = 10,
                            InUse = true,
                            Name = "Haircut"
                        },
                        new
                        {
                            Id = 33,
                            Catagory = 5,
                            InUse = false,
                            Name = "Hobbies"
                        },
                        new
                        {
                            Id = 34,
                            Catagory = 6,
                            InUse = true,
                            Name = "Home Repairs"
                        },
                        new
                        {
                            Id = 35,
                            Catagory = 8,
                            InUse = true,
                            Name = "Home School"
                        },
                        new
                        {
                            Id = 36,
                            Catagory = 9,
                            InUse = true,
                            Name = "Homeowners Ins."
                        },
                        new
                        {
                            Id = 37,
                            Catagory = 13,
                            InUse = true,
                            Name = "Internet"
                        },
                        new
                        {
                            Id = 38,
                            Catagory = 8,
                            InUse = true,
                            Name = "Kid Related"
                        },
                        new
                        {
                            Id = 39,
                            Catagory = 6,
                            InUse = true,
                            Name = "Kitchen & Bath"
                        },
                        new
                        {
                            Id = 40,
                            Catagory = 6,
                            InUse = false,
                            Name = "Laundry"
                        },
                        new
                        {
                            Id = 41,
                            Catagory = 7,
                            InUse = true,
                            Name = "Life Insurance"
                        },
                        new
                        {
                            Id = 42,
                            Catagory = 5,
                            InUse = true,
                            Name = "Mandolin"
                        },
                        new
                        {
                            Id = 43,
                            Catagory = 9,
                            InUse = true,
                            Name = "Mortgage"
                        },
                        new
                        {
                            Id = 44,
                            Catagory = 1,
                            InUse = true,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 45,
                            Catagory = 10,
                            InUse = false,
                            Name = "Moving Expenses"
                        },
                        new
                        {
                            Id = 46,
                            Catagory = 1,
                            InUse = true,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 47,
                            Catagory = 13,
                            InUse = true,
                            Name = "Natural Gas"
                        },
                        new
                        {
                            Id = 48,
                            Catagory = 6,
                            InUse = true,
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 49,
                            Catagory = 10,
                            InUse = true,
                            Name = "Other"
                        },
                        new
                        {
                            Id = 50,
                            Catagory = 5,
                            InUse = true,
                            Name = "Outdoor"
                        },
                        new
                        {
                            Id = 51,
                            Catagory = 5,
                            InUse = false,
                            Name = "Pet"
                        },
                        new
                        {
                            Id = 52,
                            Catagory = 13,
                            InUse = true,
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 53,
                            Catagory = 9,
                            InUse = true,
                            Name = "Property Taxes"
                        },
                        new
                        {
                            Id = 54,
                            Catagory = 11,
                            InUse = true,
                            Name = "Reimbursement"
                        },
                        new
                        {
                            Id = 55,
                            Catagory = 9,
                            InUse = false,
                            Name = "Rent"
                        },
                        new
                        {
                            Id = 56,
                            Catagory = 5,
                            InUse = true,
                            Name = "Running"
                        },
                        new
                        {
                            Id = 57,
                            Catagory = 10,
                            InUse = false,
                            Name = "School"
                        },
                        new
                        {
                            Id = 58,
                            Catagory = 10,
                            InUse = true,
                            Name = "Seasonal"
                        },
                        new
                        {
                            Id = 59,
                            Catagory = 5,
                            InUse = false,
                            Name = "Sewing"
                        },
                        new
                        {
                            Id = 60,
                            Catagory = 10,
                            InUse = true,
                            Name = "Shipping"
                        },
                        new
                        {
                            Id = 61,
                            Catagory = 5,
                            InUse = false,
                            Name = "Shooting"
                        },
                        new
                        {
                            Id = 62,
                            Catagory = 6,
                            InUse = true,
                            Name = "Software"
                        },
                        new
                        {
                            Id = 63,
                            Catagory = 5,
                            InUse = true,
                            Name = "Swimming"
                        },
                        new
                        {
                            Id = 64,
                            Catagory = 10,
                            InUse = false,
                            Name = "Taxes"
                        },
                        new
                        {
                            Id = 65,
                            Catagory = 6,
                            InUse = true,
                            Name = "Toiletries"
                        },
                        new
                        {
                            Id = 66,
                            Catagory = 8,
                            InUse = true,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 67,
                            Catagory = 14,
                            InUse = true,
                            Name = "Trash"
                        },
                        new
                        {
                            Id = 68,
                            Catagory = 14,
                            InUse = true,
                            Name = "Travel Misc"
                        },
                        new
                        {
                            Id = 69,
                            Catagory = 13,
                            InUse = true,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 70,
                            Catagory = 5,
                            InUse = true,
                            Name = "Weight Training"
                        },
                        new
                        {
                            Id = 71,
                            Catagory = 6,
                            InUse = true,
                            Name = "Yard"
                        });
                });

            modelBuilder.Entity("CashTrack.Data.Entities.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Catagory")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IncomeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Income");
                });

            modelBuilder.Entity("CashTrack.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Mitchellscott@me.com",
                            FirstName = "Mitchell",
                            LastName = "Scott",
                            PasswordHash = "$2a$11$254JJZ5mlBwTHkBjoLpmQ.b7PZyCGmaJ1KeBqbBnAIRK.DaQkpq3W"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Sarahscott@me.com",
                            FirstName = "Sarah",
                            LastName = "Scott",
                            PasswordHash = "$2a$11$sJsy1/bq/etwSkclwEdjzev.Xw7S7z0.aVYNtIio2OOtTVVDnu9/W"
                        });
                });

            modelBuilder.Entity("CashTrack.Data.Entities.Expense", b =>
                {
                    b.HasOne("CashTrack.Data.Entities.ExpenseCatagory", "Catagory")
                        .WithMany()
                        .HasForeignKey("CatagoryId");

                    b.Navigation("Catagory");
                });
#pragma warning restore 612, 618
        }
    }
}
