// <auto-generated />
using CashTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CashTrack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CashTrack.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Mitchellscott@me.com",
                            FirstName = "Mitchell",
                            LastName = "Scott",
                            PasswordHash = "$2a$11$VcWljRSFrFM7pK6t4.9jweRV4TgZOC.R.Zu9ER/SRDU1a2Fz06S2.",
                            ResetToken = "",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Sarahscott@me.com",
                            FirstName = "Sarah",
                            LastName = "Scott",
                            PasswordHash = "$2a$11$AXlgUd.6cIRozwe/1wt7veG08bOcE0849RVmdZ5az05fM69rfYxOW",
                            ResetToken = "",
                            Role = "Guide"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
